# Build Options

MOUSEKEY_ENABLE ?= yes       # Mouse keys(+4700)
EXTRAKEY_ENABLE ?= yes       # Audio control and System control(+450)
COMMAND_ENABLE ?= yes        # Commands for debug and configuration
NKRO_ENABLE ?= yes           # Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
AUDIO_ENABLE ?= yes          # Audio output on port C6


ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
